# Importing important libraries

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import auc, classification_report, roc_auc_score, accuracy_score
from sklearn.linear_model import LogisticRegression

# Loading datasets

In [ ]:
#loading train data
train = pd.read_csv("https://raw.githubusercontent.com/RozieH/datasets/main/Train.csv")
train.head(10)

User_ID  month  year  CompPart  Comment  Sub  Disc  Target
0  ID_XI7BAR4Y      8     3         0        0    0     0       0
1  ID_XI7BAR4Y      8     2         0        0    0     0       0
2  ID_XI7BAR4Y      9     2         0        0    0     0       0
3  ID_XI7BAR4Y      9     3         0        0    0     0       0
4  ID_XI7BAR4Y     10     3         0        0    0     0       0
5  ID_XI7BAR4Y     10     2         0        0    0     0       0
6  ID_XI7BAR4Y     11     2         1        0    0     0       1
7  ID_XI7BAR4Y     11     3         0        0    0     0       0
8  ID_XI7BAR4Y     12     2         0        0    1     0       1
9  ID_XI7BAR4Y     12     3         0        0    0     0       0

In [ ]:
#loading testdata
test = pd.read_csv("https://raw.githubusercontent.com/RozieH/datasets/main/Test.csv")
test.head()

User_ID  month  year
0  ID_H1ELY25E      1     4
1  ID_H1ELY25E      2     4
2  ID_H1ELY25E      3     4
3  ID_463Q2BCO      1     4
4  ID_463Q2BCO      2     4

In [ ]:
#loading comments data
comments = pd.read_csv("https://raw.githubusercontent.com/RozieH/datasets/main/Comments.csv")
comments.head() 

UserID  CommentDate Year  CommentDate Month  CommentDate Day_of_week
0  ID_MVIB05DL                 3                  1                        7
1  ID_MVIB05DL                 3                  1                        7
2  ID_KBRFRAR9                 3                  1                        7
3  ID_UDS6FRR8                 3                  1                        7
4  ID_UDS6FRR8                 3                  1                        7

In [ ]:
#loading CompetitionPartipation data
CompetitionPartipation = pd.read_csv("https://raw.githubusercontent.com/RozieH/datasets/main/CompetitionPartipation.csv")

df1 = CompetitionPartipation[['UserID','PublicRank','Successful Submission Count']]
CompetitionPartipation.head() 

CompID       UserID  ... CompPartCreated Month CompPartCreated Day_of_week
0  ID_WMUF  ID_UWBBZ9OF  ...                     1                           4
1  ID_MPSN  ID_UWBBZ9OF  ...                     1                           7
2  ID_WMUF  ID_1N5J2PGO  ...                     1                           5
3  ID_7MLO  ID_1N5J2PGO  ...                    10                           5
4  ID_2KEY  ID_1N5J2PGO  ...                     5                           4

[5 rows x 7 columns]

In [ ]:
#loading Competitions data
Competitions= pd.read_csv("https://raw.githubusercontent.com/RozieH/datasets/main/Competitions.csv")

df2= Competitions[['Kind','Points Reward','SecretCode']]
Competitions.head() 

CompID  Country  ... CompStartTime Month CompStartTime Day_of_week
0  ID_WGZ2  ID_HWRH  ...                   6                         5
1  ID_G370      NaN  ...                  12                         7
2  ID_R5HL      NaN  ...                  10                         4
3  ID_Y6XI  ID_ARVG  ...                  11                         4
4  ID_8PEN  ID_I1L9  ...                  11                         4

[5 rows x 17 columns]

In [ ]:
#loading Discussions data
Discussions= pd.read_csv("https://raw.githubusercontent.com/RozieH/datasets/main/Discussions.csv")
Discussions.head() 

FeatureF  DiscDate Year  ...     DiscID       UserID
0         1              3  ...  ID_Z77ETQ  ID_F2757IAI
1         0              3  ...  ID_E47JKY  ID_F2757IAI
2         1              3  ...  ID_CB4Y0N  ID_F2757IAI
3         0              3  ...  ID_BNIHCF  ID_F2757IAI
4         1              3  ...  ID_MLPYCO  ID_F2757IAI

[5 rows x 6 columns]

In [ ]:
#loading Submissions data
Submissions= pd.read_csv("https://raw.githubusercontent.com/RozieH/datasets/main/Submissions.csv")
Submissions.head() 

UserID  FeatureG  ... SubDate Month  SubDate Day_of_week
0  ID_8JP75F20         1  ...             3                    2
1  ID_8JP75F20         1  ...             3                    2
2  ID_8JP75F20         1  ...             3                    4
3  ID_8JP75F20         1  ...             3                    2
4  ID_8JP75F20         1  ...             3                    4

[5 rows x 6 columns]

In [ ]:
#loading users data
Users = pd.read_csv("https://raw.githubusercontent.com/RozieH/datasets/main/Users.csv")

df3=Users[['UserID', 'UserDate Year','UserDate Month']]
Users.head()

UserID  FeatureX  ... UserDate Month  UserDate Day_of_week
0  ID_N5LTBAPU         0  ...              4                     4
1  ID_CLSFQB0S         0  ...              5                     4
2  ID_RE6T58Y4         0  ...             12                     3
3  ID_XJQQRJV3         0  ...              9                     2
4  ID_1JHU6A8S         0  ...             10                     1

[5 rows x 8 columns]

In [ ]:
#loading SampleSubmission
SampleSubmission = pd.read_csv("https://raw.githubusercontent.com/RozieH/datasets/main/SampleSubmission.csv")
SampleSubmission.head() 

UserMonthYear  Target
0  ID_000VV0KM_1_4     NaN
1  ID_000VV0KM_2_4     NaN
2  ID_000VV0KM_3_4     NaN
3  ID_003OCIYO_1_4     NaN
4  ID_003OCIYO_2_4     NaN

In [ ]:
#loading VariableDefinitions
VariableDefinitions = pd.read_csv("https://raw.githubusercontent.com/RozieH/datasets/main/VariableDefinitions.csv")
#VariableDefinitions[(VariableDefinitions.VariableName=='FeatureA')]
pd.DataFrame(VariableDefinitions)


VariableName                                 VariableDefinition
0                                               Train                                                NaN
1                                              UserID  This is the unique ID of the user who made the...
2                                            CompPart  Value 1 if Participated in any competition in ...
3                                             Comment  Value 1 if Participated in any comments in the...
4                                                 Sub  Value 1 if Submitted to any competition in the...
..                                                ...                                                ...
67                                     UserDate Month  The month of the year the user signed up. Mont...
68                               UserDate Day_of_week  The day of the week the user signed up on. Day...
69                                                NaN                                                NaN
70                                                NaN                                                NaN
71  The variables have been masked consistently ac...                                                NaN

[72 rows x 2 columns]

# EDA - Exploratory data analysis

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 259832 entries, 0 to 259831
Data columns (total 8 columns):
 #   Column    Non-Null Count   Dtype 
---  ------    --------------   ----- 
 0   User_ID   259832 non-null  object
 1   month     259832 non-null  int64 
 2   year      259832 non-null  int64 
 3   CompPart  259832 non-null  int64 
 4   Comment   259832 non-null  int64 
 5   Sub       259832 non-null  int64 
 6   Disc      259832 non-null  int64 
 7   Target    259832 non-null  int64 
dtypes: int64(7), object(1)
memory usage: 15.9+ MB


In [ ]:
train.describe()

month           year  ...           Disc         Target
count  259832.000000  259832.000000  ...  259832.000000  259832.000000
mean        7.412116       2.690927  ...       0.014532       0.139729
std         3.355127       0.527094  ...       0.119672       0.346706
min         1.000000       1.000000  ...       0.000000       0.000000
25%         5.000000       2.000000  ...       0.000000       0.000000
50%         8.000000       3.000000  ...       0.000000       0.000000
75%        10.000000       3.000000  ...       0.000000       0.000000
max        12.000000       3.000000  ...       1.000000       1.000000

[8 rows x 7 columns]

In [ ]:
train.isna().sum()

User_ID     0
month       0
year        0
CompPart    0
Comment     0
Sub         0
Disc        0
Target      0
dtype: int64

In [ ]:
train.tail()

User_ID  month  year  CompPart  Comment  Sub  Disc  Target
259827  ID_MAP5X6D4     12     3         0        0    0     0       0
259828  ID_QHUAHU76     12     3         0        0    0     0       0
259829  ID_8IKU22O5     12     3         1        0    0     0       1
259830  ID_NHWCR1IY     12     3         0        0    0     0       0
259831  ID_XMD7EIYV     12     3         1        0    0     1       1

In [ ]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65223 entries, 0 to 65222
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   User_ID  65223 non-null  object
 1   month    65223 non-null  int64 
 2   year     65223 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 1.5+ MB


In [ ]:
test.isna().sum()

User_ID    0
month      0
year       0
dtype: int64

In [ ]:
# Concatenating files
train1=pd.merge(df3, df1, on='UserID')
df=train1.rename(columns = {'UserID':'User_ID'}, inplace = False)
df

User_ID  UserDate Year  ...  PublicRank Successful Submission Count
0      ID_N5LTBAPU              2  ...     rank 10                    count 10
1      ID_CLSFQB0S              1  ...      rank 1                     count 9
2      ID_CLSFQB0S              1  ...         NaN                         NaN
3      ID_CLSFQB0S              1  ...      rank 1                    count 10
4      ID_RE6T58Y4              2  ...     rank 11                     count 8
...            ...            ...  ...         ...                         ...
48560  ID_B8VJJMWK              2  ...      rank 4                    count 10
48561  ID_XAQGPGAZ              2  ...      rank 4                    count 10
48562  ID_1AO7PVP2              2  ...      rank 7                     count 6
48563  ID_3ZXJIREU              1  ...         NaN                         NaN
48564  ID_3ZXJIREU              1  ...     rank 10                    count 10

[48565 rows x 5 columns]

In [ ]:
#merge final data
final_df=pd.merge(df, train, on='User_ID')
final_df

User_ID  UserDate Year  UserDate Month  ... Sub Disc  Target
0       ID_N5LTBAPU              2               4  ...   0    0       0
1       ID_N5LTBAPU              2               4  ...   0    0       0
2       ID_N5LTBAPU              2               4  ...   0    0       0
3       ID_N5LTBAPU              2               4  ...   0    0       0
4       ID_N5LTBAPU              2               4  ...   0    0       0
...             ...            ...             ...  ...  ..  ...     ...
832917  ID_3ZXJIREU              1               7  ...   0    0       0
832918  ID_3ZXJIREU              1               7  ...   0    0       0
832919  ID_3ZXJIREU              1               7  ...   1    0       1
832920  ID_3ZXJIREU              1               7  ...   0    0       0
832921  ID_3ZXJIREU              1               7  ...   0    0       0

[832922 rows x 12 columns]

In [ ]:
final_df.isna().sum()

User_ID                             0
UserDate Year                       0
UserDate Month                      0
PublicRank                     573522
Successful Submission Count    537318
month                               0
year                                0
CompPart                            0
Comment                             0
Sub                                 0
Disc                                0
Target                              0
dtype: int64

In [ ]:
train=final_df.dropna()

In [ ]:
train.isna().sum()

User_ID                        0
UserDate Year                  0
UserDate Month                 0
PublicRank                     0
Successful Submission Count    0
month                          0
year                           0
CompPart                       0
Comment                        0
Sub                            0
Disc                           0
Target                         0
dtype: int64

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 259400 entries, 0 to 832921
Data columns (total 12 columns):
 #   Column                       Non-Null Count   Dtype 
---  ------                       --------------   ----- 
 0   User_ID                      259400 non-null  object
 1   UserDate Year                259400 non-null  int64 
 2   UserDate Month               259400 non-null  int64 
 3   PublicRank                   259400 non-null  object
 4   Successful Submission Count  259400 non-null  object
 5   month                        259400 non-null  int64 
 6   year                         259400 non-null  int64 
 7   CompPart                     259400 non-null  int64 
 8   Comment                      259400 non-null  int64 
 9   Sub                          259400 non-null  int64 
 10  Disc                         259400 non-null  int64 
 11  Target                       259400 non-null  int64 
dtypes: int64(9), object(3)
memory usage: 25.7+ MB


In [ ]:
train=train.drop(['User_ID'],axis=1)
# train.to_csv('sample.csv')
# from google.colab import files
# files.download('sample.csv') 

In [ ]:
train['PublicRank'].unique()

array(['rank 10', 'rank 1', 'rank 11', 'rank 7', 'rank 2', 'rank 8',
       'rank 3', 'rank 4', 'rank 5', 'rank 9', 'rank 6'], dtype=object)

In [ ]:
train['PublicRank'] = train['PublicRank'].replace(['rank 10', 'rank 1', 'rank 11', 'rank 7', 'rank 2', 'rank 8',
       'rank 3', 'rank 4', 'rank 5', 'rank 9', 'rank 6'],[10,1,11,7,2,8,3,4,5,9,6])

In [ ]:
train['Successful Submission Count'].unique()

array(['count 10', 'count 9', 'count 8', 'count 5', 'count 6', 'count 3',
       'count 7', 'count 4'], dtype=object)

In [ ]:
train['Successful Submission Count'] = train['Successful Submission Count'].replace(['count 10', 'count 9', 'count 8', 'count 5', 'count 6', 'count 3',
       'count 7', 'count 4'], [10,9,8,5,6,3,7,4])
train.head()   

UserDate Year  UserDate Month  PublicRank  ...  Sub  Disc  Target
0              2               4          10  ...    0     0       0
1              2               4          10  ...    0     0       0
2              2               4          10  ...    0     0       0
3              2               4          10  ...    0     0       0
4              2               4          10  ...    0     0       0

[5 rows x 11 columns]

In [ ]:
train['CompPart'].unique()

array([0, 1])

In [ ]:
train['Comment'].unique()

array([0, 1])

In [ ]:
train['Sub'].unique()

array([0, 1])

In [ ]:
train['Disc'].unique()

array([0, 1])

In [ ]:
# # One hot encoding of categorical variables
# one_hot_CompPart = pd.get_dummies(train['CompPart'], prefix='CompPart')


# train = pd.concat([train, one_hot_CompPart], axis=1)

# train.drop(['CompPart'], axis=1, inplace=True)


# train.head(2)

In [ ]:
# # One hot encoding comment
# one_hot_Comment = pd.get_dummies(train['Comment'], prefix='Comment')


# train = pd.concat([train, one_hot_Comment], axis=1)

# train.drop(['Comment'], axis=1, inplace=True)


# train.head(2)

In [ ]:
# # One hot encoding submission
# one_hot_Sub = pd.get_dummies(train['Sub'], prefix='Sub')


# train = pd.concat([train, one_hot_Sub], axis=1)

# train.drop(['Sub'], axis=1, inplace=True)


# train.head(2)

In [ ]:
# # One hot encoding discussion
# one_hot_Disc = pd.get_dummies(train['Disc'], prefix='Disc')


# train = pd.concat([train, one_hot_Disc], axis=1)

# train.drop(['Disc'], axis=1, inplace=True)


# train.head(2)

In [ ]:
# Scaling
# Step 1: define a MinMax scalar that will transform the data values into values in (0, 1)
# Hint: Look up the documentation for MinMaxScaler
# COMPLETE
scaler = MinMaxScaler()

# Step 2: fit the MinMaxScaler using our data 
# Hint: use .fit()
# COMPLETE
scaler.fit(train)
X_values = train.values
# Step 3: scale the values in our dataset, X_values 
# Hint: use .transform()
# COMPLETE
X_values_scaled = scaler.transform(X_values)
train = pd.DataFrame(X_values_scaled, columns=train.columns)

# Building Model

In [ ]:
#split train data into target and independent variables
X = train.drop(['Target'],axis=1)
y = train.Target

In [ ]:
# split train data into train and validate
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
    )

In [ ]:
X_test.head()

UserDate Year  UserDate Month  PublicRank  ...  Comment  Sub  Disc
146618            0.0        1.000000         0.4  ...      0.0  0.0   0.0
68428             0.0        0.363636         1.0  ...      0.0  1.0   0.0
191871            1.0        0.000000         0.9  ...      0.0  0.0   0.0
110622            0.5        0.181818         0.9  ...      1.0  1.0   0.0
253033            1.0        0.181818         0.0  ...      0.0  0.0   0.0

[5 rows x 10 columns]

In [ ]:
#Train classifier
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=1000, max_depth=100)
classifier.fit(X_train, y_train) 

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=100, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
y_train_pred = classifier.predict(X_train)

In [ ]:
# Measuring classifier performance on train
rf_preds = roc_auc_score(y_train_pred, classifier.predict_proba(X_train)[:, 1])

In [ ]:
rf_preds

1.0

In [ ]:
# measure classifier performance
# roc_auc_score(y_test, classifier.predict_proba(X_test)[:, 1])

In [ ]:
# Logistic regression
# lr = LogisticRegression(solver="liblinear", random_state=0).fit(X_train, y_train)
# roc_auc_score(y_test, lr.predict_proba(X_test)[:, 1])

In [ ]:
# y_train_pred = lr.predict(X_train)

In [ ]:
# roc_auc_score(y_train_pred, lr.predict_proba(X_train)[:, 1])

In [ ]:
# make prediction on the test set",
test_preds = classifier.predict_proba(X_test)[:, 1]
test_preds

array([0., 1., 1., ..., 0., 0., 1.])

In [ ]:
# create submission dataframe
UserMonthYear = SampleSubmission['UserMonthYear']
Submission = pd.concat([pd.DataFrame(UserMonthYear), pd.DataFrame(test_preds)], axis=1)

In [ ]:
# show sample of the submission data,
Submission.head()

UserMonthYear    0
0  ID_000VV0KM_1_4  0.0
1  ID_000VV0KM_2_4  1.0
2  ID_000VV0KM_3_4  1.0
3  ID_003OCIYO_1_4  1.0
4  ID_003OCIYO_2_4  0.0

In [ ]:
# save submission into csv file\n",
Submission.to_csv('zindi_sub.csv',index=False)

In [ ]:
from google.colab import files
files.download('zindi_sub.csv') 

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>